# Generated by Django 2.1a1 on 2018-06-02 17:48

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('thermal', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='result',
            name='condition',
        ),
        migrations.RemoveField(
            model_name='project',
            name='result',
        ),
        migrations.DeleteModel(
            name='Result',
        ),
    ]
